name: app_quran
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  get_storage: ^2.0.3
  http: ^0.13.4
  flutter_switch: 0.3.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  fonts: 
    - family: PoppinsBold
      fonts: 
        - asset: assets/fonts/Poppins-Black.ttf
    - family: PoppinsReg
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
  uses-material-design: true

